# Generated by Django 4.2.7 on 2024-01-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='dailyactivitymodel',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
