# Generated by Django 4.2.8 on 2024-01-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('size_of_housing', models.FloatField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('with_Meat', 'with meat')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('private_car_elec', 'Private_car_elec'), ('private_car_gasoline', 'Private_car_gasoline'), ('bus', 'Bus'), ('train', 'Train'), ('bike', 'Bike'), ('metro', 'Metro'), ('walk', 'Walk')], max_length=50)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='user_input.householdmodel')),
                ('lifestyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='user_input.lifestylemodel')),
                ('traffic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='user_input.trafficmodel')),
            ],
        ),
    ]
