# Generated by Django 4.2.8 on 2024-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivitymodel',
            name='traffic',
        ),
        migrations.AddField(
            model_name='dailyactivitymodel',
            name='traffic',
            field=models.ManyToManyField(related_name='daily_activities', to='user_input.trafficmodel'),
        ),
    ]
