# Generated by Django 4.2.8 on 2024-01-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_input', '0002_remove_dailyactivitymodel_traffic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivitymodel',
            name='household',
        ),
        migrations.RemoveField(
            model_name='dailyactivitymodel',
            name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='dailyactivitymodel',
            name='traffic',
        ),
    ]
