from django.db import models

class LifestyleModel(models.Model):
    LIFESTYLE_CHOICES = [
        ('vegetarian', 'Vegetarian'),
        ('vegan', 'Vegan'),
        ('with_Meat', 'with meat'),
    ]
    style = models.CharField(max_length=50, choices=LIFESTYLE_CHOICES)

    #calculate carbon emission from lifestyle, the term "factor" refers to the daily carbon emissions, measured in kilograms.
    def calculate_emission(self):
        emission_factors = {
           'vegetarian':6.57,
           'vegan':5.14,
           'with_Meat':8.71
        }
        emission = emission_factors.get(self.style, 0)
        return emission

class TrafficModel(models.Model):
    MODE_CHOICES = [
        ('private_car_elec', 'Private_car_elec'),
        ('private_car_gasoline', 'Private_car_gasoline'),
        ('bus', 'Bus'),
        ('train', 'Train'),
        ('bike', 'Bike'),
        ('metro', 'Metro'),
        ('walk', 'Walk')
    ]
    mode = models.CharField(max_length=50, choices=MODE_CHOICES)
    distance = models.FloatField()

    #calculate carbon emission from transport, the factor is measured in kilograms.
    def calculate_emission(self):
        emission_factors = {
            'private_car_elec': 0.1116, 
            'private_car_gasoline': 0.18,
            'bus': 0.02852,                   
            'train': 0.0496,   
            'metro': 0.04464,              
            'bike': 0.0285,                    
            'walk': 0,                 
        }

        emission_factor = emission_factors.get(self.mode, 0)
        return self.distance * emission_factor

class HouseholdModel(models.Model):
    number_of_people = models.IntegerField()
    size_of_housing = models.FloatField()
    country = models.CharField(max_length=100)

    #carbon emissions generated by households, 0.125kg is the daily carbon emissions generated per capita per unit of living area.
    def calculate_emission(self):

       return self.size_of_housing / self.number_of_people * 0.125

class DailyActivityModel(models.Model):
    date = models.DateField()
