# Generated by Django 4.2.7 on 2024-01-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0002_alter_dailyactivitymodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitymodel',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
