# Generated by Django 4.2.7 on 2024-01-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0003_alter_dailyactivitymodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitymodel',
            name='date',
            field=models.DateField(),
        ),
    ]
