# Generated by Django 4.2.7 on 2024-01-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0004_alter_dailyactivitymodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationresult',
            options={'ordering': ['date']},
        ),
    ]
